modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/Bloeckchengrafik/colonies-unbound/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/Bloeckchengrafik/colonies-unbound"
authors="Christian Bergschneider"
description='''
Register survival-built homes and workplaces with MineColonies.
'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecolonies"
type="required"
versionRange="[1.1.1374,1.1.1375)"
ordering="AFTER"
side="BOTH"

